### ISSUE TITLE
Implement send-email Container

### ISSUE THREAD

**Issue by vahid-dan** [FLARE-forecast/FLARE-containers#43]
We are in need of a container to send daily emails to a list of recipients including a message and a few file attachments. We should be able to run this container once a day at a specific time on the IBM Cloud.

- The container should have a similar structure as FLARE containers (naming convention, usage of Bash3 BoilerPlate, usage of config file, etc.).
- Use `s-nail` as the mail processing system.
- Set up a Gmail account on the s-nail authenticate on Gmail and send the email via Gmail.
- Encode the password for the Gmail account in the s-nail config file so that it would be secure to publish the image to the public.
- The attachments should be downloaded from S3 storage based on a filename prefix and the current date.
- The list of recipients, the filename prefix for the attachments, and the message body should be read from a config file.

**Comment by vahid-dan** [comment]
The YAML file should include the body message, the list of attachments, and the list of recipients. The lists can be of any length. For instance, we may have just one recipient or multiple recipients and we should be able to add or remove to the lists at any time.

The attachments should have a direct URL for the file (such as a URL to a raw GitHub file) or a link to an S3 object.

```yaml
body: "Body message here."
attachments:
- github-url1
- github-url2
- s3-object1
- s3-object2
- s3-object3
- github-url3
recepients:
- recepient1
- recepient2
- recepient3
```
